In [10]:
import torch
x = torch.rand(5, 3)
print(x)


tensor([[0.8782, 0.2154, 0.3234],
        [0.9543, 0.5086, 0.0508],
        [0.2077, 0.6063, 0.8669],
        [0.3831, 0.2624, 0.3033],
        [0.9170, 0.5851, 0.1426]])


In [11]:
o = torch.zeros(2,2)
print(o)

tensor([[0., 0.],
        [0., 0.]])


In [12]:

one = torch.ones(2,2)
print(one)

tensor([[1., 1.],
        [1., 1.]])


In [18]:
multi = torch.tensor([[[0,1,4],[2,3,5],[4,1,6]],[[2,3,5],[4,1,6],[5,6,8]]])
print(multi)

tensor([[[0, 1, 4],
         [2, 3, 5],
         [4, 1, 6]],

        [[2, 3, 5],
         [4, 1, 6],
         [5, 6, 8]]])


In [19]:
x =torch.tensor([1., 2.,3.,4.]) #tensor mutate only float value
y=torch.tensor([3.,4.,5.,6.])
w=torch.tensor(0.)
b=torch.tensor(0.)
y_pred = w*x+b
loss = ((y_pred-y)**2).mean()
print("predection of y", y_pred)
print("Actual value of y", y)
print(loss)

predection of y tensor([0., 0., 0., 0.])
Actual value of y tensor([3., 4., 5., 6.])
tensor(21.5000)


In [ ]:
#fixed input 
x=torch.tensor(2.0)
#leanable number
y=torch.tensor(3.0, requires_grad=True)
#predction logic
y_pred = x*y
# set some correct value as true value of y
y_true=torch.tensor(10.0)
#loss calculation
loss=(y_pred-y_true)**2

print("loss", loss)
print("prediction", y_pred.item())
print("loss", loss.item())
# move backward to check correct value 
loss.backward()
print("y.grad", y.grad)

loss tensor(16., grad_fn=<PowBackward0>)
prediction 6.0
loss 16.0
y.grad tensor(-16.)


In [ ]:
#fixed input 
x=torch.tensor(2.0)
#leanable number
y=torch.tensor(3.0, requires_grad=True)
#predction logic
y_pred = x*y
# set some correct value as true value of y
y_true=torch.tensor(10.0)
#loss calculation
loss=(y_pred-y_true)**2

print("Before update")
print("prediction", y_pred.item())
print("loss", loss.item())
# move backward to check correct value 
loss.backward()
print("gradient", y.grad.item())
lr =0.1
# update weight
with torch.no_grad(): # donot track the y
    y -= lr*y.grad
# reset the value of 
y.grad.zero_()

print("after update")
print("y value", y.item())

Before update
prediction 6.0
loss 16.0
gradient -16.0
after update
y value 4.599999904632568


In [40]:
x=torch.tensor([1.,2.,3.,4.]) # fixed numbers
y_true = torch.tensor([2.,4.,6.,8.]) # correct numbers
# learning number
w= torch.tensor(0.0, requires_grad=True)
lr =0.1
epochs=10

for epoch in range(epochs):
    # step 1 prediction
    y_pred =w * x 
    #step 2 loss calcution
    loss = ((y_pred-y_true)**2).mean()

    # loss backward check
    loss.backward()
    with torch.no_grad():
        w -= lr*w.grad

    print(f"Epoch {epoch+1}: w={w.item():.4f}, loss={loss.item():.4f}")




Epoch 1: w=3.0000, loss=30.0000
Epoch 2: w=4.5000, loss=7.5000
Epoch 3: w=2.2500, loss=46.8750
Epoch 4: w=-0.3750, loss=0.4688
Epoch 5: w=0.5625, loss=42.3047
Epoch 6: w=3.6562, loss=15.4980
Epoch 7: w=4.2656, loss=20.5737
Epoch 8: w=1.4766, loss=38.4979
Epoch 9: w=-0.5273, loss=2.0549
Epoch 10: w=1.2598, loss=47.9060


In [ ]:
import torch
import torch.nn as nn

layer = nn.Linear(3,2) # 3 input features 2 output features means 3 rows of input and and every row will have 2 value in output
x= torch.tensor([1.,2.,3.])
y = layer(x)
print(y)

"""
Neural Network - computer metthod
nn.modules
basically is having the following components
1. class structure
2. layers
3. activation functions
4. optimizer
5. save model

layers = weight  - how important the input and bias-  how much adustment in output (up or down)
activation functions - 
RLU (Reactified linear unit, - applied internal between internal layers - hidden layers
sigmoid -(yes or no) - applied to get final output - binary output
nn.Softmax - applied in multiple class model or multi options - can you used to get final output in case of multi option

optimizer - SGD - slow move and Adam - for noisy data

 """


tensor([-2.4709,  0.4666], grad_fn=<ViewBackward0>)


'\nNeural Network - computer metthod\nnn.modules\nbasically is having the following components\n1. class structure\n2. layers\n3. activation functions\n4. optimizer\n5. save model\n\nactivation functions - \nRLU (Reactified linear unit, - applied internal between internal layers - hidden layers\nsigmoid -(yes or no) - applied to get final output - binary output\nnn.Softmax - applied in multiple class model or multi options - can you used to get final output in case of multi option\n\noptimizer - SGD - slow move and Adam - for noisy data\n\n '

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.Linear = nn.Linear(1,1)

    def forward(self, x):
        return self.Linear(x)

x= torch.tensor([[1.],[2.], [3.], [4.]])
y = torch.tensor([[2.],[4.], [6.], [8.]])

model = MyModel()

loss_fn = nn.MSELoss()
# there are two kind of optimizer 1.SGD and 2. Adam example 
#x = torch.optimizer.SGD(model.parameters, 0.01) - if model require SGD optimizer, 
# and you want replace optimizer with Adam then you have pass the learning rate 10th of initial learning rate
#y= torch.optimizer.Adam(model.parameters, 0.001)
optimizer = optim.Adam(model.parameters(), lr=0.1) 

for epoch in range(10):
    optimizer.zero_grad()
    y_pred = model(x)
    loss = loss_fn(y_pred, y)
    loss.backward()
    optimizer.step()
    print(f"Epoch {epoch+1}, Loss={loss.item():.4f}")

    # save model
torch.save(model.state_dict(), "linear_model.pth")

Epoch 1, Loss=36.6095
Epoch 2, Loss=32.3295
Epoch 3, Loss=28.3278
Epoch 4, Loss=24.6086
Epoch 5, Loss=21.1748
Epoch 6, Loss=18.0282
Epoch 7, Loss=15.1689
Epoch 8, Loss=12.5952
Epoch 9, Loss=10.3037
Epoch 10, Loss=8.2888
